namespaces:
  eirini: "eirini"
  kubecf: "kubecf"
  quarksoperator: "cf-operator"
storageClass: "local-path"


system_domain: "10.86.1.11.nip.io"
creds: "testcluster"
ha: false
eirini: false
ingress: false

cf_cli_version: "6.53.0"
kubecf:
  from: "master"
  to: 3ef471889e9f4aee1c97826b0745bb64aa9c5817

settings:
  grace_sleep_time: "30"
  retries: "180"
external_ip: |
  - 10.86.1.11
cap:
  enabled: true
  kubecf:
    from:
      version: "2.2.3"
      chart: suse/kubecf
    to:
      version: "2.5.8-rc3"
      chart: suse/kubecf
  quarks:
    from:
      version: "4.5.13+0.gd4738712"
      chart: suse/cf-operator
    to:
      version: "6.1.17+0.gec409fd7-rc3"
      chart: suse/cf-operator