system_domain: {{.Values.system_domain}}
install_stacks:
  - sle15
credentials:
  cf_admin_password: {{.Values.creds}}
  uaa_admin_client_secret: {{.Values.creds}}

features:
  eirini:
    enabled: {{ .Values.eirini }}
  ingress:
    enabled: {{ .Values.ingress }}
  embedded_database:
    enabled: false
  external_database:
    enabled: true
    seed: true 
    type: mysql
    host: kubecf-mysql.kubecf-mysql.svc
    port: 3306
    databases:
      uaa:
        name: uaa
        password: test
        username: root
      cc:
        name: cloud_controller
        password: test
        username: root
      bbs:
        name: diego
        password: test
        username: root
      routing_api:
        name: routing-api
        password: test
        username: root
      policy_server:
        name: network_policy
        password: test
        username: root
      silk_controller:
        name: network_connectivity
        password: test
        username: root
      locket:
        name: locket
        password: test
        username: root
      credhub:
        name: credhub
        password: test
        username: root
kube:
  storage_class: {{.Values.storageClass}} 
high_availability: {{.Values.ha}}    

{{- if not .Values.ingress }}
#  External endpoints are created for the instance groups only if
#  features.ingress.enabled is false.
services:
  router:
    type: LoadBalancer
    externalIPs: {{ .Values.external_ip | nindent 4 }}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "{{.Values.system_domain}}, *.{{.Values.system_domain}}"
  ssh-proxy:
    type: LoadBalancer
    externalIPs: {{ .Values.external_ip | nindent 4 }}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "ssh.{{.Values.system_domain}}"
  tcp-router:
    type: LoadBalancer
    externalIPs: {{ .Values.external_ip | nindent 4 }}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "*.tcp.{{.Values.system_domain}}, tcp.{{.Values.system_domain}}"
    port_range:
      start: 20000
      end: 20008

{{- end }}

{{- if .Values.eirini  }}
{{- if not .Values.ingress  }}

eirinix:
  services:
    ssh-proxy:
      type: LoadBalancer
      externalIPs: {{ .Values.external_ip | nindent 6 }}
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "{{.Values.system_domain}}, *.{{.Values.system_domain}}"

{{- end }}
{{- end }}
