system_domain: {{.Values.system_domain}}
install_stacks:
  - sle15
credentials:
  cf_admin_password: {{.Values.creds}}
  uaa_admin_client_secret: {{.Values.creds}}

features:
  eirini:
    enabled: {{ .Values.eirini }}
  ingress:
    enabled: {{ .Values.ingress }}
  embedded_database:
    enabled: true

kube:
  storage_class: {{.Values.storageClass}} 
high_availability: {{.Values.ha}}    

{{- if not .Values.ingress }}
#  External endpoints are created for the instance groups only if
#  features.ingress.enabled is false.
services:
  router:
    type: LoadBalancer
    externalIPs: {{ .Values.external_ip | nindent 4 }}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "{{.Values.system_domain}}, *.{{.Values.system_domain}}"
  ssh-proxy:
    type: LoadBalancer
    externalIPs: {{ .Values.external_ip | nindent 4 }}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "ssh.{{.Values.system_domain}}"
  tcp-router:
    type: ClusterIP

{{- end }}

{{- if .Values.eirini  }}
{{- if not .Values.ingress  }}
eirinix:
  services:
    ssh-proxy:
      type: LoadBalancer
      externalIPs: {{ .Values.external_ip | nindent 6 }}
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "{{.Values.system_domain}}, *.{{.Values.system_domain}}"

{{- end }}
{{- end }}
