system_domain: {{.Values.system_domain}}
install_stacks:
  - sle15
credentials:
  cf_admin_password: {{.Values.creds}}
  uaa_admin_client_secret: {{.Values.creds}}

features:
  eirini:
    enabled: false
  ingress:
    enabled: true
  embedded_database:
    enabled: true
    
kube:
  storage_class: {{.Values.storageClass}} 
high_availability: {{.Values.ha}}    