name: "external-db test"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.4.0
      with:
          name: "kubecf"
    - name: Install deps
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        sudo wget https://github.com/mudler/charty/releases/download/v0.2.0/charty-0.2.0-linux-amd64 -O /usr/bin/charty
        sudo chmod +x /usr/bin/charty
        sudo apt-get install python3-venv
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        IP=$(kubectl get node kubecf-control-plane -o jsonpath='{ .status.addresses[?(@.type == "InternalIP")].address }')
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
        echo "IP: " ${IP}
        charty run testcharts/external-db --set "system_domain=$IP.nip.io" --set "external_ip=- $IP"
